module CorbaDropbox {

 	struct User
	{
		string username;
		string password;
		boolean isLoggedIn;
	};
	
	struct Document 
	{
		string filename;
		User user;
		string contents;
		boolean isPrivate;
	};
	
	typedef sequence<string> docList;
	
	interface ClientCallback
	{
		void doCallback(in string msg);
	};

	interface UserService
	{	
		boolean register (in string username, in string password);
		User login (in string username, in string password);
		
	};
	
	interface DocService
	{
		boolean uploadDoc(in Document document); 
		Document downloadDoc(in string filename, in User user);
		boolean queryDocuments(in string filename, in User user);
		docList listDocuments( );
		docList listUserDocuments(in User user);
		boolean updateDoc(in Document document, in ClientCallback updatedDoc);
	};
};