package CorbaDropbox;


/**
* CorbaDropbox/_DocServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Saturday, March 23, 2013 2:07:48 PM GMT
*/

public class _DocServiceStub extends org.omg.CORBA.portable.ObjectImpl implements CorbaDropbox.DocService
{

  public boolean uploadDoc (String filename, String contents, boolean isPrivate, CorbaDropbox.User user)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("uploadDoc", true);
                $out.write_string (filename);
                $out.write_string (contents);
                $out.write_boolean (isPrivate);
                CorbaDropbox.UserHelper.write ($out, user);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return uploadDoc (filename, contents, isPrivate, user        );
            } finally {
                _releaseReply ($in);
            }
  } // uploadDoc

  public CorbaDropbox.Document downloadDoc (String filename, CorbaDropbox.User user)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("downloadDoc", true);
                $out.write_string (filename);
                CorbaDropbox.UserHelper.write ($out, user);
                $in = _invoke ($out);
                CorbaDropbox.Document $result = CorbaDropbox.DocumentHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return downloadDoc (filename, user        );
            } finally {
                _releaseReply ($in);
            }
  } // downloadDoc

  public boolean queryDocuments (String filename, CorbaDropbox.User user)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("queryDocuments", true);
                $out.write_string (filename);
                CorbaDropbox.UserHelper.write ($out, user);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return queryDocuments (filename, user        );
            } finally {
                _releaseReply ($in);
            }
  } // queryDocuments

  public String listDocuments ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listDocuments", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listDocuments (        );
            } finally {
                _releaseReply ($in);
            }
  } // listDocuments

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CorbaDropbox/DocService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _DocServiceStub
