package CorbaDropbox;


/**
* CorbaDropbox/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corbadropbox.idl
* 06 April 2013 13:35:47 o'clock IST
*/

public interface ClientCallbackOperations 
{
  void doCallback (String msg);
} // interface ClientCallbackOperations
