package CorbaDropbox;


/**
* CorbaDropbox/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Tuesday, March 26, 2013 7:57:20 PM GMT
*/

public interface ClientCallbackOperations 
{
  void doCallback (String msg);
} // interface ClientCallbackOperations
