package CorbaDropbox;


/**
* CorbaDropbox/ClientCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Tuesday, April 2, 2013 7:08:48 PM IST
*/

public interface ClientCallback extends ClientCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientCallback
