package CorbaDropbox;


/**
* CorbaDropbox/ClientCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../CorbaDropBox.idl
* 06 April 2013 11:38:08 o'clock IST
*/

public interface ClientCallback extends ClientCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientCallback
