package CorbaDropbox;

/**
* CorbaDropbox/ClientCallbackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
<<<<<<< HEAD
* from ../corbadropbox.idl
* 06 April 2013 13:35:47 o'clock IST
=======
* from CorbaDropbox.idl
* Saturday, April 6, 2013 12:32:38 PM IST
>>>>>>> not a clue
*/

public final class ClientCallbackHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaDropbox.ClientCallback value = null;

  public ClientCallbackHolder ()
  {
  }

  public ClientCallbackHolder (CorbaDropbox.ClientCallback initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaDropbox.ClientCallbackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaDropbox.ClientCallbackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaDropbox.ClientCallbackHelper.type ();
  }

}
