package CorbaDropbox;


/**
* CorbaDropbox/docListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../CorbaDropBox.idl
* 06 April 2013 11:38:08 o'clock IST
*/

public final class docListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public docListHolder ()
  {
  }

  public docListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaDropbox.docListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaDropbox.docListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaDropbox.docListHelper.type ();
  }

}
