package CorbaDropbox;


/**
* CorbaDropbox/DocServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corbadropbox.idl
* 08 April 2013 15:43:09 o'clock IST
*/

public interface DocServiceOperations 
{
  boolean uploadDoc (CorbaDropbox.Document document);
  CorbaDropbox.Document downloadDoc (String filename, CorbaDropbox.User user);
  boolean queryDocuments (String filename, CorbaDropbox.User user);
  String[] listDocuments ();
  String[] listUserDocuments (CorbaDropbox.User user);
  boolean updateDoc (CorbaDropbox.Document document);
} // interface DocServiceOperations
