package CorbaDropbox;


/**
* CorbaDropbox/DocService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corbadropbox.idl
* 06 April 2013 13:35:48 o'clock IST
*/

public interface DocService extends DocServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DocService
