package CorbaDropbox;


/**
* CorbaDropbox/DocServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Tuesday, March 26, 2013 8:14:52 PM GMT
*/

public interface DocServiceOperations 
{
  boolean uploadDoc (CorbaDropbox.Document document, CorbaDropbox.ClientCallback updatedDoc);
  CorbaDropbox.Document downloadDoc (String filename, CorbaDropbox.User user);
  boolean queryDocuments (String filename, CorbaDropbox.User user);
  String listDocuments ();
} // interface DocServiceOperations
