package CorbaDropbox;


/**
* CorbaDropbox/DocServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Tuesday, April 2, 2013 7:08:48 PM IST
*/

public interface DocServiceOperations 
{
  boolean uploadDoc (CorbaDropbox.Document document, CorbaDropbox.ClientCallback updatedDoc);
  CorbaDropbox.Document downloadDoc (String filename, CorbaDropbox.User user);
  boolean queryDocuments (String filename, CorbaDropbox.User user);
  String listDocuments ();
  String doclist (CorbaDropbox.User user);
} // interface DocServiceOperations
