package CorbaDropbox;

/**
* CorbaDropbox/DocServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Saturday, March 23, 2013 2:07:48 PM GMT
*/

public final class DocServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaDropbox.DocService value = null;

  public DocServiceHolder ()
  {
  }

  public DocServiceHolder (CorbaDropbox.DocService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaDropbox.DocServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaDropbox.DocServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaDropbox.DocServiceHelper.type ();
  }

}
