package CorbaDropbox;

/**
* CorbaDropbox/DocumentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../CorbaDropBox.idl
* 06 April 2013 11:38:08 o'clock IST
*/

public final class DocumentHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaDropbox.Document value = null;

  public DocumentHolder ()
  {
  }

  public DocumentHolder (CorbaDropbox.Document initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaDropbox.DocumentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaDropbox.DocumentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaDropbox.DocumentHelper.type ();
  }

}
