package CorbaDropbox;


/**
* CorbaDropbox/DocumentPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Tuesday, March 26, 2013 7:57:20 PM GMT
*/

public abstract class DocumentPOA extends org.omg.PortableServer.Servant
 implements CorbaDropbox.DocumentOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_filename", new java.lang.Integer (0));
    _methods.put ("_set_filename", new java.lang.Integer (1));
    _methods.put ("_get_user", new java.lang.Integer (2));
    _methods.put ("_set_user", new java.lang.Integer (3));
    _methods.put ("_get_contents", new java.lang.Integer (4));
    _methods.put ("_set_contents", new java.lang.Integer (5));
    _methods.put ("_get_isPrivate", new java.lang.Integer (6));
    _methods.put ("_set_isPrivate", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CorbaDropbox/Document/_get_filename
       {
         String $result = null;
         $result = this.filename ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CorbaDropbox/Document/_set_filename
       {
         String newFilename = in.read_string ();
         this.filename (newFilename);
         out = $rh.createReply();
         break;
       }

       case 2:  // CorbaDropbox/Document/_get_user
       {
         CorbaDropbox.User $result = null;
         $result = this.user ();
         out = $rh.createReply();
         CorbaDropbox.UserHelper.write (out, $result);
         break;
       }

       case 3:  // CorbaDropbox/Document/_set_user
       {
         CorbaDropbox.User newUser = CorbaDropbox.UserHelper.read (in);
         this.user (newUser);
         out = $rh.createReply();
         break;
       }

       case 4:  // CorbaDropbox/Document/_get_contents
       {
         String $result = null;
         $result = this.contents ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // CorbaDropbox/Document/_set_contents
       {
         String newContents = in.read_string ();
         this.contents (newContents);
         out = $rh.createReply();
         break;
       }

       case 6:  // CorbaDropbox/Document/_get_isPrivate
       {
         boolean $result = false;
         $result = this.isPrivate ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // CorbaDropbox/Document/_set_isPrivate
       {
         boolean newIsPrivate = in.read_boolean ();
         this.isPrivate (newIsPrivate);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CorbaDropbox/Document:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Document _this() 
  {
    return DocumentHelper.narrow(
    super._this_object());
  }

  public Document _this(org.omg.CORBA.ORB orb) 
  {
    return DocumentHelper.narrow(
    super._this_object(orb));
  }


} // class DocumentPOA
