package CorbaDropbox;


/**
* CorbaDropbox/DocumentPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Tuesday, March 26, 2013 7:57:20 PM GMT
*/

public class DocumentPOATie extends DocumentPOA
{

  // Constructors

  public DocumentPOATie ( CorbaDropbox.DocumentOperations delegate ) {
      this._impl = delegate;
  }
  public DocumentPOATie ( CorbaDropbox.DocumentOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public CorbaDropbox.DocumentOperations _delegate() {
      return this._impl;
  }
  public void _delegate (CorbaDropbox.DocumentOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String filename ()
  {
    return _impl.filename();
  } // filename
  public void filename (String newFilename)
  {
    _impl.filename(newFilename);
  } // filename

  public CorbaDropbox.User user ()
  {
    return _impl.user();
  } // user
  public void user (CorbaDropbox.User newUser)
  {
    _impl.user(newUser);
  } // user

  public String contents ()
  {
    return _impl.contents();
  } // contents
  public void contents (String newContents)
  {
    _impl.contents(newContents);
  } // contents

  public boolean isPrivate ()
  {
    return _impl.isPrivate();
  } // isPrivate
  public void isPrivate (boolean newIsPrivate)
  {
    _impl.isPrivate(newIsPrivate);
  } // isPrivate

  private CorbaDropbox.DocumentOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class DocumentPOATie
