package CorbaDropbox;


/**
* CorbaDropbox/DocumentOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Saturday, March 23, 2013 2:07:48 PM GMT
*/

public interface DocumentOperations 
{
  String filename ();
  void filename (String newFilename);
  CorbaDropbox.User user ();
  void user (CorbaDropbox.User newUser);
  String contents ();
  void contents (String newContents);
  boolean isPrivate ();
  void isPrivate (boolean newIsPrivate);
} // interface DocumentOperations
