package CorbaDropbox;

/**
* CorbaDropbox/MessageServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corbadropbox.idl
* 09 April 2013 15:56:25 o'clock IST
*/

public final class MessageServerHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaDropbox.MessageServer value = null;

  public MessageServerHolder ()
  {
  }

  public MessageServerHolder (CorbaDropbox.MessageServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaDropbox.MessageServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaDropbox.MessageServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaDropbox.MessageServerHelper.type ();
  }

}
