package CorbaDropbox;


/**
* CorbaDropbox/MessageServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corbadropbox.idl
* 09 April 2013 15:56:25 o'clock IST
*/

public interface MessageServerOperations 
{
  void register (CorbaDropbox.Listener lt);
} // interface MessageServerOperations
