package CorbaDropbox;


/**
* CorbaDropbox/MessageServerPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corbadropbox.idl
* 09 April 2013 15:56:25 o'clock IST
*/

public class MessageServerPOATie extends MessageServerPOA
{

  // Constructors

  public MessageServerPOATie ( CorbaDropbox.MessageServerOperations delegate ) {
      this._impl = delegate;
  }
  public MessageServerPOATie ( CorbaDropbox.MessageServerOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public CorbaDropbox.MessageServerOperations _delegate() {
      return this._impl;
  }
  public void _delegate (CorbaDropbox.MessageServerOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void register (CorbaDropbox.Listener lt)
  {
    _impl.register(lt);
  } // register

  private CorbaDropbox.MessageServerOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class MessageServerPOATie
