package CorbaDropbox;

/**
* CorbaDropbox/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Tuesday, March 26, 2013 8:14:52 PM GMT
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaDropbox.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (CorbaDropbox.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaDropbox.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaDropbox.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaDropbox.UserHelper.type ();
  }

}
