package CorbaDropbox;


/**
* CorbaDropbox/UserOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Tuesday, March 26, 2013 7:57:20 PM GMT
*/

public interface UserOperations 
{
  String username ();
  void username (String newUsername);
  String password ();
  void password (String newPassword);
  boolean isLoggedIn ();
  void isLoggedIn (boolean newIsLoggedIn);
} // interface UserOperations
