package CorbaDropbox;


/**
* CorbaDropbox/UserService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../CorbaDropBox.idl
* 06 April 2013 11:38:08 o'clock IST
*/

public interface UserService extends UserServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UserService
