package CorbaDropbox;


/**
* CorbaDropbox/UserServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Tuesday, March 26, 2013 7:57:20 PM GMT
*/

public interface UserServiceOperations 
{
  boolean register (String username, String password);
  CorbaDropbox.User login (String username, String password);
  String doclist (CorbaDropbox.User user);
} // interface UserServiceOperations
