package CorbaDropbox;


/**
* CorbaDropbox/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Tuesday, March 26, 2013 7:57:20 PM GMT
*/

public interface User extends UserOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface User
