package CorbaDropbox;


/**
* CorbaDropbox/UserService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../CorbaDropbox.idl
* Wednesday, April 3, 2013 11:47:06 AM BST
*/

public interface UserService extends UserServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UserService
