package CorbaDropbox;


/**
* CorbaDropbox/UserPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Tuesday, March 26, 2013 7:57:20 PM GMT
*/

public abstract class UserPOA extends org.omg.PortableServer.Servant
 implements CorbaDropbox.UserOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_username", new java.lang.Integer (0));
    _methods.put ("_set_username", new java.lang.Integer (1));
    _methods.put ("_get_password", new java.lang.Integer (2));
    _methods.put ("_set_password", new java.lang.Integer (3));
    _methods.put ("_get_isLoggedIn", new java.lang.Integer (4));
    _methods.put ("_set_isLoggedIn", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CorbaDropbox/User/_get_username
       {
         String $result = null;
         $result = this.username ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CorbaDropbox/User/_set_username
       {
         String newUsername = in.read_string ();
         this.username (newUsername);
         out = $rh.createReply();
         break;
       }

       case 2:  // CorbaDropbox/User/_get_password
       {
         String $result = null;
         $result = this.password ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // CorbaDropbox/User/_set_password
       {
         String newPassword = in.read_string ();
         this.password (newPassword);
         out = $rh.createReply();
         break;
       }

       case 4:  // CorbaDropbox/User/_get_isLoggedIn
       {
         boolean $result = false;
         $result = this.isLoggedIn ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // CorbaDropbox/User/_set_isLoggedIn
       {
         boolean newIsLoggedIn = in.read_boolean ();
         this.isLoggedIn (newIsLoggedIn);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CorbaDropbox/User:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public User _this() 
  {
    return UserHelper.narrow(
    super._this_object());
  }

  public User _this(org.omg.CORBA.ORB orb) 
  {
    return UserHelper.narrow(
    super._this_object(orb));
  }


} // class UserPOA
