package CorbaDropbox;


/**
* CorbaDropbox/UserPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDropbox.idl
* Saturday, March 23, 2013 2:07:48 PM GMT
*/

public class UserPOATie extends UserPOA
{

  // Constructors

  public UserPOATie ( CorbaDropbox.UserOperations delegate ) {
      this._impl = delegate;
  }
  public UserPOATie ( CorbaDropbox.UserOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public CorbaDropbox.UserOperations _delegate() {
      return this._impl;
  }
  public void _delegate (CorbaDropbox.UserOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String username ()
  {
    return _impl.username();
  } // username
  public void username (String newUsername)
  {
    _impl.username(newUsername);
  } // username

  public String password ()
  {
    return _impl.password();
  } // password
  public void password (String newPassword)
  {
    _impl.password(newPassword);
  } // password

  public boolean isLoggedIn ()
  {
    return _impl.isLoggedIn();
  } // isLoggedIn
  public void isLoggedIn (boolean newIsLoggedIn)
  {
    _impl.isLoggedIn(newIsLoggedIn);
  } // isLoggedIn

  private CorbaDropbox.UserOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class UserPOATie
