package CorbaDropbox;


/**
* CorbaDropbox/UserServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../CorbaDropbox.idl
* Wednesday, April 3, 2013 11:47:06 AM BST
*/

public interface UserServiceOperations 
{
  boolean register (String username, String password);
  CorbaDropbox.User login (String username, String password);
} // interface UserServiceOperations
