package CorbaDropbox.DocServicePackage;


/**
* CorbaDropbox/DocServicePackage/docListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corbadropbox.idl
* 09 April 2013 15:56:25 o'clock IST
*/

public final class docListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public docListHolder ()
  {
  }

  public docListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaDropbox.DocServicePackage.docListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaDropbox.DocServicePackage.docListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaDropbox.DocServicePackage.docListHelper.type ();
  }

}
